language: node_js
node_js:
  - 12
before_install:
  - sudo apt-get -y install python3

install:
  - npm install
  - pip3 install -r ./server/requirements.txt

script:
  - echo "Hello world"
  - python3 -V