language: python
python:
  - "3.8.2"

services:
  - docker
  - postgresql

before_install:
  - nvm install 12
  - npm install -g eslint
  - python -m pip install -U --force-reinstall pip

install:
  - npm install
  - pip install -r ./server/requirements.txt
  - pip install pylint

before_script:
  - psql -c 'create database forest_integration_test;' -U postgres

script:
  - python -m unittest discover -v -s ./server -p test_*.py
  - eslint client/**/*.js
  - pylint --rcfile=./server/.pylintrc --output-format=text ./server

after_success:
  - git stash --all
  - npm install
  - npm run build_client_prod
  - docker build -t $DOCKER_USERNAME/forestgame .

deploy:
  provider: heroku 
  edge: true
  api_key: "$HEROKU_API_KEY"
  app: theforestgame
  on:
    branch: master

after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/forestgame:latest
