language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - npm install -g eslint

install:
  - npm install
  - pip install -r ./server/requirements.txt

script:
  - python -m unittest discover -v -s ./server -p test_*.py
  - eslint client/**/*.js

after_success:
  - npm run build_client_prod
  - docker build -t $DOCKER_USERNAME/forestgame .
  - echo $?