language: python
python:
  - "3.8"

install:
  - npm install
  - pip install -r ./server/requirements.txt

script:
  - python -m unittest discover -v -s ./server -p test_*.py
  - eslint client/**/*.js