language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - npm install -g eslint
  - npm install -g webpack

install:
  - npm install
  - pip install -r ./server/requirements.txt

script:
  - python -m unittest discover -v -s ./server -p test_*.py
  - eslint client/**/*.js

after_success:
  - git stash --all
  - npm run build_client_prod
  - docker build -t $DOCKER_USERNAME/forestgame .

deploy:
  provider: heroku 
  api_key: "$HEROKU_API_KEY"
  app: theforestgame
  branch: master
  skip_cleanup: true

after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/forestgame:latest
